travis:
  secure:
    BINSTAR_TOKEN: OWuI65x7CphUj5hoCIoxfWRDP7mj77SlHFC0QwR9G4o1u6wcwBbro8jH/kEHZBE2T5fdxQWduc+DABPbAK03xsidrVFFHzGQt+UA12P6U2kAxOQ9V1jHKyKBaBhtYxpo7YvESY7bhKY11dbhEWxxnz+WgfmbamqpCT+wM0YZYUP6VHThw/DNSHrMmvJ/xqqdoRnKqd9LLZ0hm8+zSqzRl+faV545OnMAcDV9OB5Hm2CHNCqkA+CF3hoX+/FTizPMd9n27gW5yX05R2GbUwvhjhejbTIGWYoa8NcCRTVSp/CpPDlLK44Vjy1yq0ueM8N1+VyFHLesQ7VqXQsH4R3LpDyY/tnAPvZibqTmVrRsAhfMIXs2FetgrSO+HN87IUw4Y0mApwGmzwKXI5TUKIv30b2Oe/BaAAP53cgR1/YFSW+9kX0Kjoo5CY9PlNWd65gOO0YfXKBo86QvL2SpaO7mpWlDQ8HOabRmS+UKyP9uVWRCMRYbTX/bp55Iqo/n5T1QhyL06ClXDtazyN1jVSAjre/2M+RTtSlm8xJZgGkn8eEyFbakHwO8Sh6i+r37gHr1MncerNIb8XwfHeiKR4OuPRDZXyTx+7ieFU2m3DlmNw3hZYi68he1NzOLc4IezIU42ifEvKvnBwYLPbdaXfTxku5XB8TkB/SpOF0EwXeIH78=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
