travis:
  secure:
    BINSTAR_TOKEN: KkImPO8QMdqL46j3gfF9iCFudpTnKCgOIg6sCDDgFZT6PuEeSmuAUcHV/5D1l+gWvrX7z7m1cLKXq4i5uYnb6vzd8fWem6fiEQJN0D3wQUmi27YXg7XtwLbp5p2jpIwNSBZX5lNu9vUjO/xE6fUIqUNuUWge4ti2GGmxIRXH98JXMU91IloMyfIXxNf9B9YJhny0v5ctxL+qZ2OYGGDu6W7gddZ9QQg8cuWxTJSFZOea8BnqfhHSxeNs3INAPlhU71X+l9/EYpzWbl5ExRP4288GBs4ztiAFp+aM0ubbRtyhiYTqPpwKz03Bh40FQovKADzCdkR3VVhz0DE7RnFh2UBW97jwmHwY7A4al+xHPrDzwwOKrEx8eltiKu0blDDnv7CoKQR3KS+xfSAVaAeimiaVfIjiiCiK71xcId6559mR2t+InzYH5RMjfg0HBWSWQfKx5KLdYqhR+A4AKfpDqwOeBYCDy+ez8SQRjRe6zN9xgwJedSMOmacTiehAuU/m7jbU//aCWZMZ7JATVabSPmBXujhvIi/al8et9O98THcp4y5ogDeaarMWn0F+8Rvfjysky03Swzn4GkAEgZZfCTqMojKH+r947ToZg9Igv8P2Z7mBtBvpxfrYd8Ges/Ts7WurPBK9jAig3kgg1pF295vwpJc/HKk7piltQxXVRoA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
